### PR TITLE
Remove unnecessary checks identified by reviewer

### PR DESCRIPTION
**Pull request by kdnilsen**
A previous pull request was integrated before all of the reviewer
comments had been addressed.  This commit addresses the lingering
request.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)
 * @ysramakrishna (no known github.com user name / role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah pull/146/head:pull/146` \
`$ git checkout pull/146`

Update a local copy of the PR: \
`$ git checkout pull/146` \
`$ git pull https://git.openjdk.org/shenandoah pull/146/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 146`

View PR using the GUI difftool: \
`$ git pr show -t 146`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/146.diff">https://git.openjdk.org/shenandoah/pull/146.diff</a>

</details>

### CODE REVIEW

**Comment by ysramakrishna** [comment]
For context, could you link to the previous reviewer feedback that this addresses? Thanks!

**Comment by kdnilsen** [comment]
See https://github.com/openjdk/shenandoah/pull/145/files/0d8c092e209f61f91ccb41312a028769147d0f4c#r906297895

for context of original feedback

**Review by earthling-amzn — APPROVED** [review]
Thanks for the update

**Review by ysramakrishna — APPROVED** [review]
Thanks for the context. This looks good!

**Pull request closed without merging**
