### PR TITLE
Do not reset learning cycles after resizing

### PR DESCRIPTION
**Pull request by earthling-amzn**
Also, require more than 10 gc cycles before trigger can resize generations. The behavior on the extremem 'phased' workload looks much better:
```
[1334.381s][info][gc,stats       ]    66 Successful Concurrent GCs
[1334.381s][info][gc,stats       ]       0 invoked explicitly
[1334.381s][info][gc,stats       ]       0 invoked implicitly
[1334.381s][info][gc,stats       ] 
[1334.381s][info][gc,stats       ]     7 Completed Old GCs
[1334.381s][info][gc,stats       ]       0 mixed
[1334.381s][info][gc,stats       ]       0 interruptions
[1334.381s][info][gc,stats       ] 
[1334.381s][info][gc,stats       ]     1 Degenerated GCs
[1334.381s][info][gc,stats       ]       1 caused by allocation failure
[1334.381s][info][gc,stats       ]         1 happened at Mark
[1334.381s][info][gc,stats       ]       1 upgraded to Full GC
[1334.381s][info][gc,stats       ] 
[1334.381s][info][gc,stats       ]     0 Abbreviated GCs
[1334.381s][info][gc,stats       ] 
[1334.381s][info][gc,stats       ]     1 Full GCs
[1334.381s][info][gc,stats       ]       0 invoked explicitly
[1334.381s][info][gc,stats       ]       0 invoked implicitly
[1334.381s][info][gc,stats       ]       0 caused by allocation failure
[1334.381s][info][gc,stats       ]       1 upgraded from Degenerated GC
```
The full cycle here was the first cycle after the last of the initial learning cycles.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewers
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Author)
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah pull/203/head:pull/203` \
`$ git checkout pull/203`

Update a local copy of the PR: \
`$ git checkout pull/203` \
`$ git pull https://git.openjdk.org/shenandoah pull/203/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 203`

View PR using the GUI difftool: \
`$ git pr show -t 203`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/203.diff">https://git.openjdk.org/shenandoah/pull/203.diff</a>

</details>

### CODE REVIEW

**Review by ysramakrishna — APPROVED** [review]
LGTM, reviewed. But curious if you noticed any difference wrt, e.g., specjbb.

Some more thoughts:
I wonder if the # of cycles to wait would be proportional to the long-run ratio of minor to major collection cycles.

I agree though that waiting about 10 cycles between resizing decisions would have the salubrious effect of smoothing out any temporary spikes. Somewhat relatedly, and something that I only vaguely paid attention to before: What's the default decay factor for the MMU decaying average, and what constitutes an MMU sample: the occurrence of a GC (minor or major), or just a synchronous 5-second sample of both (which might decay very quickly to zero, losing almost all the information in the signal after 6-7 samples, i.e. 30-35 seconds in this case).

**Review by kdnilsen — APPROVED** [review]
Thanks.  This looks like a very good improvement.

(I assume we are separately looking into the case where the MMU triggers cause young to expand even when a more enlightened perspective would instead expand OLD.)

**Comment by earthling-amzn** [comment]
@ysramakrishna , I didn't notice the trouble with these learning cycles originally because on specjbb, the heuristic quickly maxes out the young generation size and keeps it there. The decay factor is set by `ShenandoahAdaptiveDecayFactor` (default is 0.5) and the MMU is updated every `GCPauseIntervalMillis` (default is 5 seconds).

@kdnilsen , I will look for workloads that defeat the heuristic. It's much better behaved now on the extremem 'phased' workload. Perhaps heapothesys with a high occupancy rate?

**Pull request closed without merging**
