### PR TITLE
8309874: NMethod barriers may remain armed when regions are promoted in place

### PR DESCRIPTION
**Pull request by earthling-amzn**
Genshen runs in-place promotions during the evacuation phase. If the cycle is _only_ performing in-place promotions, it should not arm NMethod barriers. The barriers are now only armed and disarmed if the collection set is not empty.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8309874](https://bugs.openjdk.org/browse/JDK-8309874): NMethod barriers may remain armed when regions are promoted in place (**Bug** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Committer) ⚠️ Review applies to [fac642a3](https://git.openjdk.org/shenandoah/pull/286/files/fac642a3a3c72c55eecab7d17ffe820016b1d5d5)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/286/head:pull/286` \
`$ git checkout pull/286`

Update a local copy of the PR: \
`$ git checkout pull/286` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/286/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 286`

View PR using the GUI difftool: \
`$ git pr show -t 286`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/286.diff">https://git.openjdk.org/shenandoah/pull/286.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/286#issuecomment-1591945172)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Thanks for fixing this.

**Comment by ysramakrishna** [comment]
Is this a performance improvement, or does not fixing this lead to buggy behaviour?

It sounded like in the case where the collection set isn't empty the nmethod barriers are disarmed as a consequence of some actions that would be skipped when the collection set is empty, thus leaving the nmethod barriers armed past that point? Could you point out the paths where the disarming happens in that case, and add it as a comment perhaps in the `arm` and `disarm` methods, so that this protocol is clearly documented?

Thanks!

**Comment by earthling-amzn** [comment]
This addresses an assert on our 17 branches, but I suspect it is a performance improvement as well.

**Review by ysramakrishna — APPROVED** [review]
Thanks for adding the comment!

**Comment by ysramakrishna** [comment]
> This addresses an assert on our 17 branches (the assert was removed along with the nmethod sweeper), but I suspect it fixes a performance regression as well.

Is there a natural place for the assert? (Can it be asserted in an appropriate heap verification perhaps?) Doesn't need to be done here, but wondering about how to make this future-proof via an assertion/check.

**Pull request closed without merging**
