### PR TITLE
Merge shenandoah:genshen

### PR DESCRIPTION
**Pull request by earthling-amzn**
Brought mainline (master) commits in a series of smaller merges to make the conflicts more manageable. The refactoring of concurrent mark and the control thread required some non-trivial conflict resolution. I've tested `satb` mode and `generational` mode on the dacapo suite.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Error
&nbsp;⚠️ Merge PRs can only be created by known OpenJDK authors.

### Download
`$ git fetch https://git.openjdk.java.net/shenandoah pull/14/head:pull/14`
`$ git checkout pull/14`

### CODE REVIEW

**Review by rkennke — CHANGES_REQUESTED** [review]
This is impossible to actually review, so I'm limited to testing it:
it finds the following compilation failure. It's probably lacking in include there. Make sure to test with --disable-precompiled-headers.

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-server_libjvm_objs_BUILD_LIBJVM_link:
/usr/bin/ld: /home/rkennke/src/openjdk/shenandoah/build/linux-x86_64-server-fastdebug/hotspot/variant-server/libjvm/objs/shenandoahScanRemembered.o: in function `ShenandoahDirectCardMarkRememberedSet::ShenandoahDirectCardMarkRememberedSet(CardTable*, unsigned long)':
/home/rkennke/src/openjdk/shenandoah/src/hotspot/share/gc/shenandoah/shenandoahScanRemembered.cpp:33: undefined reference to `ShenandoahHeap::heap()'
collect2: error: ld returned 1 exit status

* All command lines available in /home/rkennke/src/openjdk/shenandoah/build/linux-x86_64-server-fastdebug/make-support/failure-logs.
=== End of repeated output ===

**Comment by earthling-amzn** [comment]
Taking a look now. The bot suggests changing the title of this PR to indicate that it's a merge, otherwise it will be squashed. If this gets squashed, won't it make subsequent merges from master more difficult? Is it okay with you if I change the title of this PR so this goes into a `genshen` as a merge and not a giant squashed commit?

**Comment by earthling-amzn** [comment]
Well, the bot doesn't like having this PR titled as a "merge".

**Comment by rkennke** [comment]
> Taking a look now. The bot suggests changing the title of this PR to indicate that it's a merge, otherwise it will be squashed. If this gets squashed, won't it make subsequent merges from master more difficult? Is it okay with you if I change the title of this PR so this goes into a `genshen` as a merge and not a giant squashed commit?

Yes, please!

**Comment by earthling-amzn** [comment]
The bot says only 'known authors' can create merge requests.

**Comment by rkennke** [comment]
I've integrated this merge directly. Seemed the easiest approach :-)

**Pull request merged**
