### PR TITLE
8344320: GenShen: Possible null pointer usage in shGenerationalHeap

### PR DESCRIPTION
**Pull request by kdnilsen**
Certain threads, including the vm thread and Shenandoah's control thread, do not have PLABs.  There are scenarios where each may need to allocate old-gen memory on the slow-path of the load reference barrier.  This PR fixes an assumption in the allocator that assumed all threads have plabs.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8344320](https://bugs.openjdk.org/browse/JDK-8344320): GenShen: Possible null pointer usage in shGenerationalHeap (**Bug** - P4)

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/543/head:pull/543` \
`$ git checkout pull/543`

Update a local copy of the PR: \
`$ git checkout pull/543` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/543/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 543`

View PR using the GUI difftool: \
`$ git pr show -t 543`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/543.diff">https://git.openjdk.org/shenandoah/pull/543.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/543#issuecomment-2486131601)
</details>

### CODE REVIEW

**Comment by kdnilsen** [comment]
Currently running regression tests.  Will not integrate until all tests succeed.

**Review by earthling-amzn — APPROVED** [review]
Looks good to me.

**Comment by earthling-amzn** [comment]
Not sure why this PR is pulling in 27 commits, I don't think it matters, but in the future try creating new branches with:
```
% git fetch <shenandoah>
% git switch -c <new-branch-name> <shenandoah>/master
```
Replace `<shenandoah>` with your remote name for `https://github.com/openjdk/shenandoah`.

**Review by ysramakrishna — APPROVED** [review]

**Pull request closed without merging**
