### PR TITLE
Young refproc test

### PR DESCRIPTION
**Pull request by wadehenn**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Roman Kennke](https://openjdk.java.net/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/shenandoah pull/42/head:pull/42` \
`$ git checkout pull/42`

Update a local copy of the PR: \
`$ git checkout pull/42` \
`$ git pull https://git.openjdk.java.net/shenandoah pull/42/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 42`

View PR using the GUI difftool: \
`$ git pr show -t 42`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/shenandoah/pull/42.diff">https://git.openjdk.java.net/shenandoah/pull/42.diff</a>

</details>

### CODE REVIEW

**Comment by robilad** [comment]
Hi,

Please send an e-mail to Dalibor.Topic@oracle.com so that Incan mark your account as verified.

**Comment by wadehenn** [comment]
I need to have my account verified. -wade

**Comment by wadehenn** [comment]
This is my first pull request

**Review by rkennke — APPROVED** [review]

**Comment by rkennke** [comment]
Owner of PR is no longer an active contributor.

**Pull request closed without merging**
