### PR TITLE
8318057: GenShen: investigate small refactor of remset swap code

### PR DESCRIPTION
**Pull request by ysramakrishna**
Some closures were being unnecessarily applied to free regions rather than just to allocated old and young regions. Restrict the closure application to old and young regions as appropriate, eliminating extra generation affiliation checks in some closures. Also fixed a slightly incorrect documentation comment.

Replaced use of integer division with right shifts. Added a few useful assertions associated with these operations.

However, neither of these made any measurable difference to the performance of the bulk operations on the card table.

**Testing:**

- [x] jtreg and stress tests in test pipeline helper
- [x] locally tested with jtreg hotsot_gc tests and with specjbb with and without heap verification
- [x] no performance improvements noted; gathering more data, see ticket for latest updates

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8318057](https://bugs.openjdk.org/browse/JDK-8318057): GenShen: investigate small refactor of remset swap code (**Task** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Committer)
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/342/head:pull/342` \
`$ git checkout pull/342`

Update a local copy of the PR: \
`$ git checkout pull/342` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/342/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 342`

View PR using the GUI difftool: \
`$ git pr show -t 342`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/342.diff">https://git.openjdk.org/shenandoah/pull/342.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/342#issuecomment-1767708747)

### CODE REVIEW

**Comment by kdnilsen** [comment]
Do we see any performance improvement from these changes?   Has this passed the internal pipeline tests?

**Review by kdnilsen — APPROVED** [review]
Thanks for quick turnaround

**Comment by ysramakrishna** [comment]
> Do we see any performance improvement from these changes?

No, none. I left some comments & data in the JBS ticket. I am looking at gathering some more data as well a further small improvement which also is unlikely to improve performance by much.

> Has this passed the internal pipeline tests?

Yes. It's failure equivalent to the reference/baseline. (Each exhibits one failure in a particular stress test w/dacapo that is under active investigation in a separate ticket by William, I believe.)

**Comment by ysramakrishna** [comment]
> Thanks for quick turnaround

Thanks for the prompt review, Kelvin. I've updated the description and am making this a draft again to try a couple more improvements, and to gather some performance data along the lines described in the ticket.

**Review by kdnilsen — APPROVED** [review]
Thanks.

**Review by earthling-amzn — APPROVED** [review]

**Pull request closed without merging**
