### PR TITLE
Reduce the number of new product flags

### PR DESCRIPTION
**Pull request by shipilev**
Eventual upstreaming would require a CSR for every changed product flag. Not every flag we have now needs to be product, we can reduce them to be experimental.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewers
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Author)
 * [Roman Kennke](https://openjdk.org/census#rkennke) (@rkennke - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/251/head:pull/251` \
`$ git checkout pull/251`

Update a local copy of the PR: \
`$ git checkout pull/251` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/251/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 251`

View PR using the GUI difftool: \
`$ git pr show -t 251`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/251.diff">https://git.openjdk.org/shenandoah/pull/251.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/251#issuecomment-1503235939)

### CODE REVIEW

**Review by ysramakrishna — APPROVED** [review]
LGTM.

I suppose this doesn't preclude making them product in the future should the need arise.

Reviewed!

**Review by rkennke — APPROVED** [review]
Looks good to me. Thank you!

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
