### PR TITLE
8330071: GenShen: Allow old to expand again at end of each GC

### PR DESCRIPTION
**Pull request by kdnilsen**
This corrects errors in the implementations of max_size_for(OLD) and min_size_for(OLD).  These errors were preventing expansion of OLD in preparation for subsequent mixed-evacuation cycles.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8330071](https://bugs.openjdk.org/browse/JDK-8330071): GenShen: Allow old to expand again at end of each GC (**Bug** - P3)

### Reviewers
 * [William Kemper](https://openjdk.org/census#wkemper) (@earthling-amzn - Committer) ⚠️ Review applies to [f23113f5](https://git.openjdk.org/shenandoah/pull/421/files/f23113f503e6d5e90cdd52f16552ae9cd49cfa23)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/421/head:pull/421` \
`$ git checkout pull/421`

Update a local copy of the PR: \
`$ git checkout pull/421` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/421/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 421`

View PR using the GUI difftool: \
`$ git pr show -t 421`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/421.diff">https://git.openjdk.org/shenandoah/pull/421.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/421#issuecomment-2049959368)

### CODE REVIEW

**Comment by kdnilsen** [comment]
It would appear that our existing CI performance pipeline tests are not sufficiently sensitive to failure to expand OLD when necessary to support mixed evacuations.  Here's a test that does show good sensitivity.

On existing master, the results are:
```
Customer Preparation Processing[100000]: P50(295) P95(448) P99(768) P99.9(58408) P99.99(351320) P99.999(414070) P100(424719)

[1145.223s][info   ][gc,stats       ] 12939 Completed GCs
[1145.223s][info   ][gc,stats       ] 12894 Successful Concurrent GCs (99.65%)
[1145.223s][info   ][gc,stats       ]    12 Completed Old GCs (0.09%)
[1145.223s][info   ][gc,stats       ]      96 mixed
[1145.223s][info   ][gc,stats       ]    30 Degenerated GCs (0.23%)
[1145.223s][info   ][gc,stats       ]     4 Full GCs (0.03%)
```
With this PR, I get:
```
Customer Preparation Processing[100000]: P50(293) P95(414) P99(484) P99.9(738) P99.99(4977) P99.999(103219) P100(113555)

[1145.299s][info   ][gc,stats    ]   844 Completed GCs
[1145.299s][info   ][gc,stats    ]   828 Successful Concurrent GCs (98.10%)
[1145.299s][info   ][gc,stats    ]    14 Completed Old GCs (1.66%)
[1145.299s][info   ][gc,stats    ]     238 mixed
[1145.299s][info   ][gc,stats    ]     2 Degenerated GCs (0.24%)
[1145.299s][info   ][gc,stats    ]     0 Full GCs (0.00%)
```
The test is Extremem based:
```
~/github/shenandoah.allow-old-to-expand-again/build/linux-x86_64-server-release/jdk/bin/java \
  -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -Xms3g -Xmx3g \
  -XX:+UseShenandoahGC \
  -XX:ShenandoahGCMode=generational -XX:+UnlockExperimentalVMOptions \
  -XX:-ShenandoahPacing -XX:+UsePerfData \
  -XX:ShenandoahGuaranteedYoungGCInterval=12000 \
  -Xlog:"gc*=info,ergo" \
  -XX:+UnlockDiagnosticVMOptions \
  -XX:-UseCompressedOops -XX:-UseCompressedClassPointers \
  -XX:+UnlockExperimentalVMOptions \
  -jar ~/github/heapothesys/Extremem/target/extremem-1.0-SNAPSHOT.jar \
  -dInitializationDelay=60s -dDictionarySize=400000 -dNumCustomers=350000 \
  -dNumProducts=12000 -dCustomerThreads=200 -dCustomerPeriod=2s -dCustomerThinkTime=1s \
  -dKeywordSearchCount=4 -dServerThreads=5 -dServerPeriod=1s -dProductNameLength=10 \
  -dBrowsingHistoryQueueCount=5 \
  -dSalesTransactionQueueCount=5 \
  -dProductDescriptionLength=64 -dProductReplacementPeriod=5s -dProductReplacementCount=3500 \
  -dCustomerReplacementPeriod=5s -dCustomerReplacementCount=4000 -dBrowsingExpiration=1m \
  -dPhasedUpdates=true \
  -dPhasedUpdateInterval=30s \
  -dSimulationDuration=18m -dResponseTimeMeasurements=100000

```

**Review by earthling-amzn — APPROVED** [review]

**Review by ysramakrishna — COMMENTED** [review]
What would go wrong if, as indicated in your comments, you were to return `heap - min_young` for `max(old)`, and `heap - max_young` for `min(old)` ?

If nothing would go wrong, why not do that? If something would go wrong if one did that, may be that needs to be documented along with the comment you added.

**Comment by kdnilsen** [comment]
@ysramakrishna : Nothing would go wrong.  It's just more computation for no increased value.  Before transferring regions from generation src to generation dest, we confirm that the proposed transfer does not violate minimum size of src generation or maximum size of dest generation.

**Review by ysramakrishna — APPROVED** [review]

**Comment by kdnilsen** [comment]
Thanks @ysramakrishna for your suggestion.  I will make this change.  Am retesting before integration.

**Review by ysramakrishna — APPROVED** [review]
Thanks... LGTM! 🚢

**Pull request closed without merging**
