### PR TITLE
8327388: GenShen: census during marking is partial

### PR DESCRIPTION
**Pull request by ysramakrishna**
There was a bug in the placement of the call to clear stale census data before starting a fresh one for a new marking cycle that marks through the younger generation. This bug resulted in the use of a co-terminal suffix of the census collection, losing all data from the earlier iterations of an iterative collection process that may run up to 5 times.

We stumbled upon the defect when working on a refactoring task involving separation of generational extensions of Shenandoah from its non-generational version. The (performance) defect has existed since day zero of the adaptive tenuring code in GenShen.

Along with fixing the defect, an assertion has been added to check the "reasonable completeness" of the census, which came in useful to detect a reset call inadvertently left behind in one place.

Some ShenandoahAgeCensus APIs have been narrowed and cleaned up a bit, and documentation clarified a bit more.

**Testing**:
- [x] GHA 
- [x] Code pipeline testing : one intermittent stress dacapo failure, ascribed to an existing bug in coalesce-and-fill
- [x] SPECjbb

**Performance**: 
- [x] SPECjbb : the variance in tests fails any significant change under 2-tailed Mann-Whitney

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8327388](https://bugs.openjdk.org/browse/JDK-8327388): GenShen: census during marking is partial (**Bug** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Committer) ⚠️ Review applies to [d6edca1e](https://git.openjdk.org/shenandoah/pull/403/files/d6edca1eab771a752870c416f444cb8926997b1e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/403/head:pull/403` \
`$ git checkout pull/403`

Update a local copy of the PR: \
`$ git checkout pull/403` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/403/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 403`

View PR using the GUI difftool: \
`$ git pr show -t 403`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/403.diff">https://git.openjdk.org/shenandoah/pull/403.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/403#issuecomment-1982229839)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Thanks. LGTM.

**Comment by ysramakrishna** [comment]
After the fixing of some of the upstream issues that had snuck in, the testing is all green now. I'll rerun the performance measurements and update the description in the PR. If all goes well, we plan to intergrate it as soon as performance numbers are at hand.

**Comment by ysramakrishna** [comment]
No performance differences were noted; however, the previous census was partial and therefore potentially incorrect. A correct census should allow for future performance tuning.

**Comment by ysramakrishna** [comment]
Note: The linux-64/test (tier1) runtime failure is just an infra failure to upload test results. The tests all passed as verified from the test info:
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg:tier1_runtime              642   642     0     0   
==============================
TEST SUCCESS
```

So the red x against the linux-64/tier1_runtime can be ignored.

**Comment by ysramakrishna** [comment]
The tests were all successful after latest merge as well (see note above). There were no changes after the most recent review, which is current.

/integrate

**Pull request closed without merging**
