### PR TITLE
8318053: GenShen: Control thread may ignore requests to start concurrent GC

### PR DESCRIPTION
**Pull request by earthling-amzn**
If a request to interrupt an old cycle is accepted, but there is an allocation failure before the requested cycle begins, then the control thread may become stuck in a state where it believes it should ignore further concurrent cycle requests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8318053](https://bugs.openjdk.org/browse/JDK-8318053): GenShen: Control thread may ignore requests to start concurrent GC (**Bug** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Committer)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah.git pull/339/head:pull/339` \
`$ git checkout pull/339`

Update a local copy of the PR: \
`$ git checkout pull/339` \
`$ git pull https://git.openjdk.org/shenandoah.git pull/339/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 339`

View PR using the GUI difftool: \
`$ git pr show -t 339`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah/pull/339.diff">https://git.openjdk.org/shenandoah/pull/339.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah/pull/339#issuecomment-1760552447)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Thanks for figuring this out.

**Review by ysramakrishna — APPROVED** [review]
Thanks for the extra logging!

Changes look good to me.

Can you add into the ticket the command-line that was used for inducing the errant behavior?

Also can you add into this PR how you tested to confirm that it no longer occurs after the fix?

Thanks!

**Comment by earthling-amzn** [comment]
I updated the ticket with the command we used to reproduce it. I've seen the issue on the first run and @kdnilsen has seen it usually before the 10th run. If I can get 50 runs without the issue, I'll consider it fixed. 

Also, the additional logging showed the `_preeption_requested` flag was stuck on, when it shouldn't have been.

**Pull request closed without merging**
